### PR TITLE
Add onchannelclose handler + test + docs

### PR DESCRIPTION
**Pull request by telamon**
An stream.onchannelclose handler to complement the stream.ondiscoverykey handler.

As a stream-owner i'm using this to detect when channels that were indirectly created - become closed.
```js
const myStream = new Protocol(true, { 
  onchannelclosed: console.log.bind(null, 'channel closed')
})

feed.replicate({ stream: myStream }) // indirect channel created / can't pass my own 'onclose` handler
```

### CODE REVIEW

**Comment by mafintosh** [comment]
Can you explain the use case for this a bit more?

**Comment by telamon** [comment]
So i'm thinking to build a replication queue to limit the amount of simultaneously open channels on a protocol-stream. 

This is to mitigate scenarios where you have a large enough number of feeds that the replication bootstrap causes your node-process to choke. (Have 2000+ feeds but only ~50 are allowed to be _actively_ replicating at any one time) 

So keeping track of when a feed starts replicating is simple cause I initiate the replication process, but I was thinking to use `onchannelclosed` handler to detect when a datastructure has finished catching up and i can free up a replication slot to start replicating the next feed in queue.

Maybe there's an easier to do this that i'm not seeing?

**Comment by mafintosh** [comment]
No that makes sense. Follow up, why do you need a stream wide listener vs just listening onclose per channel?

**Comment by telamon** [comment]
Streamwide or per channel dosen't  really matter I think.
but as i wrote in the code snippet above, I don't have control over the channel creation.

When a slot is available, I'd like to 'lend' the stream to the next datastructure using `ds.replicate({ stream })`.

A streamwide onclose handler here is actually a bit painful because It forces me to map the closed key back to an 'opened' datastructure.key , and I would have to ignore any potential nested channels.

So I'm not really sure that what i'm attempting is going to work, but exposing a streamwide onchannelclose listener was the best i came up with without modifying the `replicate()` standard with something like:

```
datastructure.replicate({
  stream,
  ondone: err => console.log.bind(null, 'replication finished', err)
})
```

**Comment by mafintosh** [comment]
7.3.0

**Pull request merged**
