### PR TITLE
Add debug output

### PR DESCRIPTION
**Pull request by pfrazee**
This PR adds a debug output with the `debug` module. Run `DEBUG=hypercore_protocol npm test` to see it in action.

@mafintosh If you could, look through the PR and add any more events or information that you think would help with debugging.

### CODE REVIEW

**Comment by pfrazee** [comment]
@mafintosh updated to use the `debug` module, ready for you to take a pass

**Comment by mafintosh** [comment]
👍 👍 👍

**Comment by mafintosh** [comment]
Looks good. We can always tweak the output as we use it.

**Comment by mafintosh** [comment]
4.7.0

**Pull request merged**
