### PR TITLE
swap out crypto for specific modules

### PR DESCRIPTION
**Pull request by substack**
This patch makes the browser payload much smaller.

Before:

```
$ browserify . | wc -c
783998
```
After:

```
$ browserify . | wc -c
398897
```

### CODE REVIEW

**Comment by mafintosh** [comment]
whoa

**Comment by mafintosh** [comment]
4.3.1

**Comment by substack** [comment]
should help with https://github.com/mafintosh/hypercore/issues/26

**Comment by juliangruber** [comment]
awesome!

**Pull request merged**
